### ISSUE TITLE
Can't build TensorFlow Lite libraries for macOS

### ISSUE THREAD

**Issue by chatsopond** [asus4/tf-lite-unity-sample#212]
**Environment (please complete the following information):**
 - Architecture: Apple Silicon
 - OS/OS Version: macOS 12.3.1
 - Source Version: v2.8.0
 - Xcode Version: 13.3.1

**Describe the bug**
Cannot build TensorFlow Lite libraries for macOS

**To Reproduce**
1. Place TensorFlow folder next to the tf-lite-unity-sample-2.8.0
2. Open Terminal
3. Run `cd` to `tensorflow` and `./configure` say `y` for iOS
4. Run `cd` to `tf-lite-unity-sample-2.8.0`
5. Run `./build_tflite.py --tfpath ../tensorflow -macOS` or `./build_tflite.py --tfpath ../tensorflow -macos -xnnpack`
6. Error

```
Build macOS
bazel build --config=macos --cpu=darwin -c opt --define tflite_with_xnnpack=false tensorflow/lite/c:tensorflowlite_c
bazel build --config=macos --cpu=darwin_arm64 -c opt --define tflite_with_xnnpack=false tensorflow/lite/c:tensorflowlite_c
lipo -create -output /##<-path->##/tf-lite-unity-sample-2.8.0/Packages/com.github.asus4.tflite/Plugins/macOS/libtensorflowlite_c.dylib bazel-out/darwin-opt/bin/tensorflow/lite/c/libtensorflowlite_c.dylib bazel-out/darwin_arm64-opt/bin/tensorflow/lite/c/libtensorflowlite_c.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: one of -create, -thin <arch_type>, -extract <arch_type>, -remove <arch_type>, -replace <arch_type> <file_name>, -verify_arch <arch_type> ... , -archs, -info, or -detailed_info must be specified
usage: lipo <input_file> <command> [<options> ...]
  command is one of:
    -archs
    -create
    -detailed_info
    -extract <arch_type> [-extract <arch_type> ...]
    -extract_family <arch_type> [-extract_family <arch_type> ...]
    -info
    -remove <arch_type> [-remove <arch_type> ...]
    -replace <arch_type> <file_name> [-replace <arch_type> <file_name> ...]
    -thin <arch_type>
    -verify_arch <arch_type> ...
  options are one or more of:
    -arch <arch_type> <input_file>
    -hideARM64
    -output <output_file>
    -segalign <arch_type> <alignment>
Traceback (most recent call last):
  File "./build_tflite.py", line 125, in <module>
    build_mac(args.xnnpack)
  File "./build_tflite.py", line 37, in build_mac
    run_cmd(f'lipo -create -output {PLUGIN_PATH}/macOS/libtensorflowlite_c.dylib bazel-out/darwin-opt/{dylib_bin_path} bazel-out/darwin_arm64-opt/{dylib_bin_path}')
  File "./build_tflite.py", line 16, in run_cmd
    return subprocess.check_output(args, cwd=TENSORFLOW_PATH, universal_newlines=True, shell=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lipo', '-create', '-output', '/##<-path->##/tf-lite-unity-sample-2.8.0/Packages/com.github.asus4.tflite/Plugins/macOS/libtensorflowlite_c.dylib', 'bazel-out/darwin-opt/bin/tensorflow/lite/c/libtensorflowlite_c.dylib', 'bazel-out/darwin_arm64-opt/bin/tensorflow/lite/c/libtensorflowlite_c.dylib']' returned non-zero exit status 1.
```

**Comment by asus4** [comment]
Thanks for reporting it, @chatsopond. I confirmed the error. In the latest Xcode, the required `lipo` options seem to be changed. I will fix it.

**Comment by asus4** [comment]
macOS build is fixed in this commit
https://github.com/asus4/tf-lite-unity-sample/pull/228/commits/d8ed4b01bd9ebba1cfe177d5cbf70b9664137321
