### ISSUE TITLE
Crashing app in mobile

### ISSUE THREAD

**Issue by azn802** [asus4/tf-lite-unity-sample#43]
Unity version : 2019.3.3f1
Platform : Mobile(Android)

App crashing after 4 minutes.
Any help would be appreciated even if it is not related to this.
Thank you.

<Error Log>
2020-07-29 11:50:38.357 28624-28624/? E/MtpService: onCreate.
2020-07-29 11:50:38.358 28624-28624/? E/MtpService: mContext is NULL so getting the getApplicationContext
2020-07-29 11:50:38.359 28624-28624/? E/MtpService: < MTP > Registering BroadCast registerBroadCastPolicyRec :::::
2020-07-29 11:50:38.361 28624-28624/? E/MtpService: < MTP > Registering BroadCast registerBroadCastEmergencyRec :::::
2020-07-29 11:50:38.362 28624-28624/? E/MtpService: onStartCommand.
2020-07-29 11:50:38.362 28624-28646/? E/MtpService: handleMessage. msg= { when=0 what=0 arg1=3 target=com.samsung.android.MtpApplication.MtpService$ServiceHandler }
2020-07-29 11:50:38.378 28624-28646/? E/MtpService: mContext is NULL so getting the getApplicationContext

2020-07-29 11:50:41.419 27014-28558/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:615807374>, App: com.google.android.apps.maps, Service: oauth2:https://www.googleapis.com/auth/mobilemaps.firstparty https://www.googleapis.com/auth/notifications
rpt: Long live credential not available.
at gde.a(:com.google.android.gms@202414037@20.24.14 (120400-319035315):18)
at gbn.a(:com.google.android.gms@202414037@20.24.14 (120400-319035315):124)
at cro.a(:com.google.android.gms@202414037@20.24.14 (120400-319035315):238)
at cro.a(:com.google.android.gms@202414037@20.24.14 (120400-319035315):111)
at cro.a(:com.google.android.gms@202414037@20.24.14 (120400-319035315):246)
at cpm.onTransact(:com.google.android.gms@202414037@20.24.14 (120400-319035315):5)
at android.os.Binder.transact(Binder.java:914)
at ctj.onTransact(:com.google.android.gms@202414037@20.24.14 (120400-319035315):2)
at android.os.Binder.transact(Binder.java:914)
at aadb.onTransact(:com.google.android.gms@202414037@20.24.14 (120400-319035315):17)
at android.os.Binder.execTransactInternal(Binder.java:1021)
at android.os.Binder.execTransact(Binder.java:994)
2020-07-29 11:50:41.420 27014-28558/? W/Auth: [GetToken] GetToken failed with status code: BadAuthentication
2020-07-29 11:50:41.467 1260-1352/? E/Watchdog: !@Sync 3813 [2020-07-29 11:50:41.465] FD count : 582, wdog_way : pwdt

**Comment by asus4** [comment]
Can you share the full log? the log above is not related to the Unity app's crash.

**Comment by azn802** [comment]
[ErrorOnlyLog.txt](https://github.com/asus4/tf-lite-unity-sample/files/4993304/ErrorOnlyLog.txt)
[FullLog.txt](https://github.com/asus4/tf-lite-unity-sample/files/4993305/FullLog.txt)

I added several codes for my app(in Unity), so maybe this could be an error. I think.

**Comment by ArthurAtlantico** [comment]
Check all lines containing SQLite, these errors are likely not related to tf lite. E.g.:

android.database.sqlite.SQLiteException: no such table: TaskLock (code 1 SQLITE_ERROR[1]): , while compiling: SELECT  * FROM TaskLock
